# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'pyqt_application_form.ui'
#
# Created by: PyQt5 UI code generator 5.13.1
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1200, 800)
        MainWindow.setMinimumSize(QtCore.QSize(800, 600))
        MainWindow.setStyleSheet("* {\n"
"    font-family: \'Microsoft YaHei UI\', sans-serif\n"
"}\n"
"")
        self.central_widget = QtWidgets.QWidget(MainWindow)
        self.central_widget.setObjectName("central_widget")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.central_widget)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.widget = QtWidgets.QWidget(self.central_widget)
        self.widget.setStyleSheet("")
        self.widget.setObjectName("widget")
        self.verticalLayout_2.addWidget(self.widget)
        MainWindow.setCentralWidget(self.central_widget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1200, 15))
        self.menubar.setMinimumSize(QtCore.QSize(0, 10))
        self.menubar.setObjectName("menubar")
        self.menu_file = QtWidgets.QMenu(self.menubar)
        self.menu_file.setObjectName("menu_file")
        self.menu_help = QtWidgets.QMenu(self.menubar)
        self.menu_help.setObjectName("menu_help")
        self.menu_view = QtWidgets.QMenu(self.menubar)
        self.menu_view.setObjectName("menu_view")
        self.menuToggle = QtWidgets.QMenu(self.menu_view)
        self.menuToggle.setObjectName("menuToggle")
        MainWindow.setMenuBar(self.menubar)
        self.sidebar = QtWidgets.QDockWidget(MainWindow)
        self.sidebar.setMinimumSize(QtCore.QSize(300, 200))
        self.sidebar.setObjectName("sidebar")
        self.sidebar_content = QtWidgets.QWidget()
        self.sidebar_content.setObjectName("sidebar_content")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.sidebar_content)
        self.verticalLayout.setObjectName("verticalLayout")
        self.tab_widget = QtWidgets.QTabWidget(self.sidebar_content)
        self.tab_widget.setObjectName("tab_widget")
        self.tab_1 = QtWidgets.QWidget()
        self.tab_1.setObjectName("tab_1")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.tab_1)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label = QtWidgets.QLabel(self.tab_1)
        self.label.setObjectName("label")
        self.horizontalLayout.addWidget(self.label)
        self.lineEdit = QtWidgets.QLineEdit(self.tab_1)
        self.lineEdit.setObjectName("lineEdit")
        self.horizontalLayout.addWidget(self.lineEdit)
        self.pushButton_2 = QtWidgets.QPushButton(self.tab_1)
        self.pushButton_2.setMaximumSize(QtCore.QSize(40, 16777215))
        self.pushButton_2.setObjectName("pushButton_2")
        self.horizontalLayout.addWidget(self.pushButton_2)
        self.pushButton = QtWidgets.QPushButton(self.tab_1)
        self.pushButton.setObjectName("pushButton")
        self.horizontalLayout.addWidget(self.pushButton)
        self.verticalLayout_4.addLayout(self.horizontalLayout)
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.label_2 = QtWidgets.QLabel(self.tab_1)
        self.label_2.setObjectName("label_2")
        self.verticalLayout_3.addWidget(self.label_2)
        self.listWidget = QtWidgets.QListWidget(self.tab_1)
        self.listWidget.setObjectName("listWidget")
        self.verticalLayout_3.addWidget(self.listWidget)
        self.verticalLayout_4.addLayout(self.verticalLayout_3)
        self.tab_widget.addTab(self.tab_1, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.tab_widget.addTab(self.tab_2, "")
        self.verticalLayout.addWidget(self.tab_widget)
        self.sidebar.setWidget(self.sidebar_content)
        MainWindow.addDockWidget(QtCore.Qt.DockWidgetArea(1), self.sidebar)
        self.action_quit = QtWidgets.QAction(MainWindow)
        self.action_quit.setObjectName("action_quit")
        self.action_about = QtWidgets.QAction(MainWindow)
        self.action_about.setObjectName("action_about")
        self.action_filetab = QtWidgets.QAction(MainWindow)
        self.action_filetab.setObjectName("action_filetab")
        self.action_filetab_2 = QtWidgets.QAction(MainWindow)
        self.action_filetab_2.setObjectName("action_filetab_2")
        self.action_Empty = QtWidgets.QAction(MainWindow)
        self.action_Empty.setObjectName("action_Empty")
        self.menu_file.addAction(self.action_quit)
        self.menu_help.addAction(self.action_about)
        self.menuToggle.addAction(self.action_Empty)
        self.menu_view.addAction(self.action_filetab)
        self.menu_view.addAction(self.action_filetab_2)
        self.menu_view.addSeparator()
        self.menu_view.addAction(self.menuToggle.menuAction())
        self.menubar.addAction(self.menu_file.menuAction())
        self.menubar.addAction(self.menu_view.menuAction())
        self.menubar.addAction(self.menu_help.menuAction())

        self.retranslateUi(MainWindow)
        self.tab_widget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "PyQt Demo"))
        self.menu_file.setTitle(_translate("MainWindow", "&File"))
        self.menu_help.setTitle(_translate("MainWindow", "&Help"))
        self.menu_view.setTitle(_translate("MainWindow", "&View"))
        self.menuToggle.setTitle(_translate("MainWindow", "Toggle"))
        self.label.setText(_translate("MainWindow", "Path"))
        self.pushButton_2.setText(_translate("MainWindow", "..."))
        self.pushButton.setText(_translate("MainWindow", "&Open"))
        self.label_2.setText(_translate("MainWindow", "Recent"))
        self.tab_widget.setTabText(self.tab_widget.indexOf(self.tab_1), _translate("MainWindow", "Tab 1"))
        self.tab_widget.setTabText(self.tab_widget.indexOf(self.tab_2), _translate("MainWindow", "Tab 2"))
        self.action_quit.setText(_translate("MainWindow", "&Quit"))
        self.action_about.setText(_translate("MainWindow", "&About..."))
        self.action_filetab.setText(_translate("MainWindow", "File Tab"))
        self.action_filetab_2.setText(_translate("MainWindow", "Download Tab"))
        self.action_Empty.setText(_translate("MainWindow", "(Empty)"))
